More shards for long jobs

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -144,7 +144,7 @@ jobs:
 
 
   test-isaaclab-tasks:
-    name: isaaclab_tasks (1/2)
+    name: isaaclab_tasks (1/3)
     runs-on: [self-hosted, gpu]
     timeout-minutes: 180
     continue-on-error: true
@@ -172,23 +172,23 @@ jobs:
         dockerfile-path: docker/Dockerfile.base
         cache-tag: cache-base
 
-    - name: Run IsaacLab Tasks Tests 1/2
+    - name: Run isaaclab_tasks Tests (1/3)
       uses: ./.github/actions/run-tests
       with:
         test-path: "tools"
         result-file: "${{ github.job }}-report.xml"
-        container-name: "isaac-lab-tasks-test-${{ github.run_id }}-${{ github.run_attempt }}"
+        container-name: "isaac-lab-tasks-1-test-${{ github.run_id }}-${{ github.run_attempt }}"
         image-tag: ${{ env.DOCKER_IMAGE_TAG }}
         pytest-options: ""
         filter-pattern: "isaaclab_tasks"
         shard-index: "0"
-        shard-count: "2"
+        shard-count: "3"
 
-    - name: Upload IsaacLab Tasks Test Results
+    - name: Upload Test Results
       uses: actions/upload-artifact@v4
       if: always()
       with:
-        name: isaaclab-tasks-test-results
+        name: isaaclab-tasks-1-test-results
         path: reports/${{ github.job }}-report.xml
         retention-days: 1
         compression-level: 9
@@ -197,7 +197,6 @@ jobs:
       if: github.event.pull_request.head.repo.full_name != github.repository
       run: |
         if [ -f "reports/${{ github.job }}-report.xml" ]; then
-          # Check if the test results contain any failures
           if grep -q 'failures="[1-9]' reports/${{ github.job }}-report.xml || grep -q 'errors="[1-9]' reports/${{ github.job }}-report.xml; then
             echo "Tests failed for PR from fork. The test report is in the logs. Failing the job."
             exit 1
@@ -209,7 +208,7 @@ jobs:
 
 
   test-isaaclab-tasks-2:
-    name: isaaclab_tasks (2/2)
+    name: isaaclab_tasks (2/3)
     runs-on: [self-hosted, gpu]
     timeout-minutes: 180
     continue-on-error: true
@@ -237,7 +236,7 @@ jobs:
         dockerfile-path: docker/Dockerfile.base
         cache-tag: cache-base
 
-    - name: Run IsaacLab Tasks Tests 2/2
+    - name: Run isaaclab_tasks Tests (2/3)
       uses: ./.github/actions/run-tests
       with:
         test-path: "tools"
@@ -256,9 +255,9 @@ jobs:
           test_environments_with_stage_in_memory.py,
           test_rendering_correctness.py
         shard-index: "1"
-        shard-count: "2"
+        shard-count: "3"
 
-    - name: Upload IsaacLab Tasks 2 Test Results
+    - name: Upload Test Results
       uses: actions/upload-artifact@v4
       if: always()
       with:
@@ -271,7 +270,70 @@ jobs:
       if: github.event.pull_request.head.repo.full_name != github.repository
       run: |
         if [ -f "reports/${{ github.job }}-report.xml" ]; then
-          # Check if the test results contain any failures
+          if grep -q 'failures="[1-9]' reports/${{ github.job }}-report.xml || grep -q 'errors="[1-9]' reports/${{ github.job }}-report.xml; then
+            echo "Tests failed for PR from fork. The test report is in the logs. Failing the job."
+            exit 1
+          fi
+        else
+          echo "No test results file found. This might indicate test execution failed."
+          exit 1
+        fi
+
+
+  test-isaaclab-tasks-3:
+    name: isaaclab_tasks (3/3)
+    runs-on: [self-hosted, gpu]
+    timeout-minutes: 180
+    continue-on-error: true
+    needs: [build, detect-changes]
+    if: >-
+      always() && needs.build.result == 'success' && (
+        needs.detect-changes.outputs.isaaclab-tasks == 'true' ||
+        needs.detect-changes.outputs.isaaclab-core == 'true' ||
+        needs.detect-changes.outputs.infra == 'true'
+      )
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+        lfs: true
+
+    - name: Pull image from ECR
+      uses: ./.github/actions/ecr-build-push-pull
+      with:
+        image-tag: ${{ env.DOCKER_IMAGE_TAG }}
+        isaacsim-base-image: ${{ env.ISAACSIM_BASE_IMAGE }}
+        isaacsim-version: ${{ env.ISAACSIM_BASE_VERSION }}
+        dockerfile-path: docker/Dockerfile.base
+        cache-tag: cache-base
+
+    - name: Run isaaclab_tasks Tests (3/3)
+      uses: ./.github/actions/run-tests
+      with:
+        test-path: "tools"
+        result-file: "${{ github.job }}-report.xml"
+        container-name: "isaac-lab-tasks-3-test-${{ github.run_id }}-${{ github.run_attempt }}"
+        image-tag: ${{ env.DOCKER_IMAGE_TAG }}
+        pytest-options: ""
+        filter-pattern: "isaaclab_tasks"
+        shard-index: "2"
+        shard-count: "3"
+
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v4
+      if: always()
+      with:
+        name: isaaclab-tasks-3-test-results
+        path: reports/${{ github.job }}-report.xml
+        retention-days: 1
+        compression-level: 9
+
+    - name: Check Test Results for Fork PRs
+      if: github.event.pull_request.head.repo.full_name != github.repository
+      run: |
+        if [ -f "reports/${{ github.job }}-report.xml" ]; then
           if grep -q 'failures="[1-9]' reports/${{ github.job }}-report.xml || grep -q 'errors="[1-9]' reports/${{ github.job }}-report.xml; then
             echo "Tests failed for PR from fork. The test report is in the logs. Failing the job."
             exit 1
@@ -283,7 +345,7 @@ jobs:
 
 
   test-isaaclab-core:
-    name: isaaclab (core) (1/2)
+    name: isaaclab (core) (1/3)
     runs-on: [self-hosted, gpu]
     timeout-minutes: 180
     needs: [build, detect-changes]
@@ -309,7 +371,7 @@ jobs:
         dockerfile-path: docker/Dockerfile.base
         cache-tag: cache-base
 
-    - name: Run IsaacLab Core Tests (1/2)
+    - name: Run isaaclab (core) Tests (1/3)
       uses: ./.github/actions/run-tests
       with:
         test-path: "tools"
@@ -319,7 +381,7 @@ jobs:
         pytest-options: ""
         filter-pattern: "not isaaclab_"
         shard-index: "0"
-        shard-count: "2"
+        shard-count: "3"
 
     - name: Upload Test Results
       uses: actions/upload-artifact@v4
@@ -345,7 +407,7 @@ jobs:
 
 
   test-isaaclab-core-2:
-    name: isaaclab (core) (2/2)
+    name: isaaclab (core) (2/3)
     runs-on: [self-hosted, gpu]
     timeout-minutes: 180
     needs: [build, detect-changes]
@@ -371,7 +433,7 @@ jobs:
         dockerfile-path: docker/Dockerfile.base
         cache-tag: cache-base
 
-    - name: Run IsaacLab Core Tests (2/2)
+    - name: Run isaaclab (core) Tests (2/3)
       uses: ./.github/actions/run-tests
       with:
         test-path: "tools"
@@ -381,13 +443,75 @@ jobs:
         pytest-options: ""
         filter-pattern: "not isaaclab_"
         shard-index: "1"
-        shard-count: "2"
+        shard-count: "3"
 
     - name: Upload Test Results
       uses: actions/upload-artifact@v4
       if: always()
       with:
         name: isaaclab-core-2-test-results
+        path: reports/${{ github.job }}-report.xml
+        retention-days: 1
+        compression-level: 9
+
+    - name: Check Test Results for Fork PRs
+      if: github.event.pull_request.head.repo.full_name != github.repository
+      run: |
+        if [ -f "reports/${{ github.job }}-report.xml" ]; then
+          if grep -q 'failures="[1-9]' reports/${{ github.job }}-report.xml || grep -q 'errors="[1-9]' reports/${{ github.job }}-report.xml; then
+            echo "Tests failed for PR from fork. The test report is in the logs. Failing the job."
+            exit 1
+          fi
+        else
+          echo "No test results file found. This might indicate test execution failed."
+          exit 1
+        fi
+
+
+  test-isaaclab-core-3:
+    name: isaaclab (core) (3/3)
+    runs-on: [self-hosted, gpu]
+    timeout-minutes: 180
+    needs: [build, detect-changes]
+    if: >-
+      always() && needs.build.result == 'success' && (
+        needs.detect-changes.outputs.isaaclab-core == 'true' ||
+        needs.detect-changes.outputs.infra == 'true'
+      )
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
+        lfs: true
+
+    - name: Pull image from ECR
+      uses: ./.github/actions/ecr-build-push-pull
+      with:
+        image-tag: ${{ env.DOCKER_IMAGE_TAG }}
+        isaacsim-base-image: ${{ env.ISAACSIM_BASE_IMAGE }}
+        isaacsim-version: ${{ env.ISAACSIM_BASE_VERSION }}
+        dockerfile-path: docker/Dockerfile.base
+        cache-tag: cache-base
+
+    - name: Run isaaclab (core) Tests (3/3)
+      uses: ./.github/actions/run-tests
+      with:
+        test-path: "tools"
+        result-file: "${{ github.job }}-report.xml"
+        container-name: "isaac-lab-core-3-test-${{ github.run_id }}-${{ github.run_attempt }}"
+        image-tag: ${{ env.DOCKER_IMAGE_TAG }}
+        pytest-options: ""
+        filter-pattern: "not isaaclab_"
+        shard-index: "2"
+        shard-count: "3"
+
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v4
+      if: always()
+      with:
+        name: isaaclab-core-3-test-results
         path: reports/${{ github.job }}-report.xml
         retention-days: 1
         compression-level: 9
@@ -1086,7 +1210,7 @@ jobs:
 
 
   combine-results:
-    needs: [build, build-curobo, detect-changes, test-isaaclab-tasks, test-isaaclab-tasks-2, test-isaaclab-core, test-isaaclab-core-2, test-isaaclab-rl, test-isaaclab-mimic, test-isaaclab-contrib, test-isaaclab-teleop, test-isaaclab-visualizers, test-isaaclab-assets, test-isaaclab-newton, test-isaaclab-physx, test-curobo, test-quarantined, test-environments-training]
+    needs: [build, build-curobo, detect-changes, test-isaaclab-tasks, test-isaaclab-tasks-2, test-isaaclab-tasks-3, test-isaaclab-core, test-isaaclab-core-2, test-isaaclab-core-3, test-isaaclab-rl, test-isaaclab-mimic, test-isaaclab-contrib, test-isaaclab-teleop, test-isaaclab-visualizers, test-isaaclab-assets, test-isaaclab-newton, test-isaaclab-physx, test-curobo, test-quarantined, test-environments-training]
     runs-on: ubuntu-latest
     if: always()
     name: Combine Results
@@ -1104,31 +1228,45 @@ jobs:
       run: |
         mkdir -pv reports
 
-    - name: Download Test Results
+    - name: Download isaaclab_tasks (1/3) Test Results
       uses: actions/download-artifact@v4
       with:
-        name: isaaclab-tasks-test-results
+        name: isaaclab-tasks-1-test-results
         path: reports/
       continue-on-error: true
 
-    - name: Download IsaacLab Tasks 2 Test Results
+    - name: Download isaaclab_tasks (2/3) Test Results
       uses: actions/download-artifact@v4
       with:
         name: isaaclab-tasks-2-test-results
         path: reports/
       continue-on-error: true
 
-    - name: Download IsaacLab Core 1 Test Results
+    - name: Download isaaclab_tasks (3/3) Test Results
+      uses: actions/download-artifact@v4
+      with:
+        name: isaaclab-tasks-3-test-results
+        path: reports/
+      continue-on-error: true
+
+    - name: Download isaaclab (core) (1/3) Test Results
       uses: actions/download-artifact@v4
       with:
         name: isaaclab-core-1-test-results
         path: reports/
       continue-on-error: true
 
-    - name: Download IsaacLab Core 2 Test Results
+    - name: Download isaaclab (core) (2/3) Test Results
       uses: actions/download-artifact@v4
       with:
         name: isaaclab-core-2-test-results
+        path: reports/
+      continue-on-error: true
+
+    - name: Download isaaclab (core) (3/3) Test Results
+      uses: actions/download-artifact@v4
+      with:
+        name: isaaclab-core-3-test-results
         path: reports/
       continue-on-error: true
 
