update

diff --git a/.github/workflows/license-check.yaml b/.github/workflows/license-check.yaml
--- a/.github/workflows/license-check.yaml
+++ b/.github/workflows/license-check.yaml
@@ -16,8 +16,8 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Install jq
-      run: sudo apt-get update && sudo apt-get install -y jq
+    # - name: Install jq
+    #   run: sudo apt-get update && sudo apt-get install -y jq
 
     - name: Set up Python
       uses: actions/setup-python@v4
@@ -60,8 +60,8 @@ jobs:
         # Split ALLOWED_LICENSES into individual words
         IFS=' ' read -r -a allowed_licenses <<< "$ALLOWED_LICENSES"
 
-        jq -e '.[] | select(.package | test("GitPython"))' $EXCEPTIONS_FILE
-        echo "jq exit code: $?"
+        # jq -e '.[] | select(.package | test("GitPython"))' $EXCEPTIONS_FILE
+        # echo "jq exit code: $?"
 
         # Loop through the installed packages and their licenses
         for pkg in $(jq -r '.[].Name' licenses.json); do
